### ISSUE TITLE
ukb Broken Pipe on Linux

### ISSUE THREAD

**Issue by jmugan** [dkmfbk/pikes#9]
When I run `process.sh` on Amazon Linux, I get

```
20:03:29.076 [client-00] INFO  eu.fbk.fcw.ukb.UKB_MT - Trying to restart UKB [1/50]
20:03:29.077 [client-00] WARN  eu.fbk.fcw.ukb.UKB_MT - Broken pipe
java.io.IOException: Broken pipe
	at java.io.FileOutputStream.writeBytes(Native Method)
	at java.io.FileOutputStream.write(FileOutputStream.java:326)
	at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
	at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
	at eu.fbk.fcw.ukb.UKB_MT.run(UKB_MT.java:144)
	at eu.fbk.fcw.ukb.UKBAnnotator.annotate(UKBAnnotator.java:56)
	at edu.stanford.nlp.pipeline.AnnotationPipeline.annotate(AnnotationPipeline.java:76)
	at edu.stanford.nlp.pipeline.StanfordCoreNLP.annotate(StanfordCoreNLP.java:605)
	at eu.fbk.dkm.pikes.tintop.AnnotationPipeline.parseAll(AnnotationPipeline.java:1026)
	at eu.fbk.dkm.pikes.tintop.AnnotationPipeline.parseAll(AnnotationPipeline.java:993)
	at eu.fbk.dkm.pikes.tintop.AnnotationPipeline.parseFromString(AnnotationPipeline.java:1059)
	at eu.fbk.dkm.pikes.tintop.FolderOrchestrator$LocalTintopClient.run(FolderOrchestrator.java:115)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

It creates the naf files, but a lot seems to be missing, such as links to SUMO and Wordnet. Do you know what is happening?

**Comment by jmugan** [comment]
I tried recompiling Pikes from source following the instructions at the bottom of http://pikes.fbk.eu/download.html. 

The utils install alright, but the second part, fcw, gives the error 
```
[ERROR] Failed to execute goal on project fcw-udpipe-api: Could not resolve dependencies for project eu.fbk.fcw:fcw-udpipe-api:jar:1.0-SNAPSHOT: 
The following artifacts could not be resolved: eu.fbk.utils:utils-core:jar:3.2-SNAPSHOT, eu.fbk.utils:utils-gson:jar:3.2-SNAPSHOT, eu.fbk.utils:utils-corenlp:jar:3.2-SNAPSHOT: 
Failure to find eu.fbk.utils:utils-core:jar:3.2-SNAPSHOT in https://raw.githubusercontent.com/fbk/mvn-repo/master/releases was cached in the local repository, 
resolution will not be reattempted until the update interval of fbk-repo has elapsed or updates are forced -> [Help 1]
```
I got this same error when I tried it both on a Mac and an Amazon Linux instance.

**Comment by rospocher** [comment]
Hi Jonathan,

thanks for testing PIKES!
There are two separate problems here, I guess: (i) the compiled version of UKB provided in the download package is not compatible with the Amazon Linux architecture; and (ii) re-compiling PIKES via maven is currently broken due to some restructuring of the maven dependencies in our code.

Let's try to fix the first (if needed, we can provide a way to recompile PIKES from sources in the next days).

Start from a "clean" version of the download package: https://knowledgestore.fbk.eu/files/pikes/download/pikes-all.tar.gz
To be sure that you are facing a binary compatibility problem related to UKB, try this command from the shell from within the ukb main folder (the one inside the pikes folder):

`echo -e "ctx_01\napple#n#w1#1\nctx_02\nbe#v#workaround#1\n" | \
    ./ukb_wsd  --ppr -K models/wnet30_wnet30g_rels.bin \
               -D models/wnet30_dict.txt --allranks -
    !! -v 2.0 ./ukb_wsd --ppr -K models/wnet30_wnet30g_rels.bin -D`

It should return something like this:

`!! -v 2.0 ./ukb_wsd --ppr -K models/wnet30_wnet30g_rels.bin -D
models/wnet30_dict.txt --allranks - <STDIN>
ctx_01 w1  07739125-n/0.818818 12633994-n/0.181182 !! apple
ctx_02 workaround  02620587-v/0.423094 02604760-v/0.357271
02603699-v/0.0593929 02655135-v/0.0551626 02702508-v/0.0223217
02697725-v/0.0184291 02664769-v/0.013024 02445925-v/0.0127932
02614181-v/0.011015 02744820-v/0.0100322 02268246-v/0.00740436
02749904-v/0.00508079 02616386-v/0.00497906 !! be`

If not, then UKB has to be recompiled from sources.

Download the source version of UKB and recompile it following the instructions in the "Running PIKES on a Mac OS X" (they works also for a different linux architecture - just be careful to follow the precise instruction on which files to copy from the recompiled binary to the ukb folder under the pikes folder, i.e.: "copy compile_kb, convert2.0, ukb_ppv and ukb_wsd to the ukb/ folder in the pikes folder").
Try again testing UKB as described above. If it works, the try launching again the process.sh PIKES command.

Please, let us know if it works.
Marco

**Comment by jmugan** [comment]
Hi Marco, thanks so much for helping me.

I already thought to do the Mac OS procedure to recompile UKB for the Amazon Linux, but the result was the same with the `eu.fbk.fcw.ukb.UKB_MT - Broken pipe` error. I may have made a mistake when copying one of the files, so I'll try your command tonight.

It would be good to be able to compile Pikes from source so we can make changes. I don't know how many changes need to be made in the POMs and such. Thanks again! Pikes is beautiful!

**Comment by jmugan** [comment]
When I ran your command on the clean download, I got `-bash:  ./ukb_wsd: No such file or directory`. I'm in the right directory, I think, because I see `./ukb_wsd`. When I just run `./ukb_wsd` it says `-bash: ./ukb_wsd: cannot execute binary file`.

When I went into the UKB I was trying to compile and tried to run ./ukb_wsd I got the error
`./ukb_wsd: error while loading shared libraries: libboost_program_options.so.1.66.0: cannot open shared object file: No such file or directory`
I tried recompiling but had all kinds of other problems with Boost. 
I tried `./configure --with-boost-include=/usr/include` and that seemed to work fine, but when I did `make` I got the error 
```
g++ -O2 -Wall -Wno-deprecated -D UKB_SERVER -o ukb_walkandprint ukb_walkandprint.cc common.o globalVars.o ukbServer.o configFile.o fileElem.o kbGraph.o kbGraph_common.o kbGraph_v16.o disambGraph.o csentence.o wdict.o walkandprint.o -I /usr/include  -lboost_program_options -lboost_system -lboost_filesystem -lboost_random -lpthread
fileElem.o: In function `ukb::File_elem::fill(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
fileElem.cc:(.text+0x302): undefined reference to `boost::filesystem::path::lexically_normal() const'
```

And same error when I used `--with-boost-include=/usr/local/include` and also when I downloaded UKB directly from that Github.

I'll try switching to Ubuntu.

**Comment by jmugan** [comment]
Okay, I moved over to Ubuntu, and I got it working! I still had to recompile UKB. I used Boost version 1.58. It was probably the newer version of Boost (1.66) that was giving me the compile error above (although that was on Amazon Linux, so who knows).

**Comment by rospocher** [comment]
Hi Jonathan,

glad that you have it working on Ubuntu!
I've tried recompiling UKB on Mac. I've recompiled the UKB source files, both trying with
- those included in PIKES under `ukb/ukb/src`
- the latest UKB version on git `https://github.com/asoroa/ukb/tree/master/src`

with boost/1.67.0_1 (obtained via homebrew), and it works.
It may be a problem specific of boost 1.66 or the Amazon linux architecture (maybe some other missing dependencies?).
Good that we have a note on this on the issue tracker for future reference.
Thanks for reporting it!
Marco

**Comment by pandemosth** [comment]
For anyone else that comes across this, I ran into the same issue on Amazon Linux and found that copying over the ukb files (as per the OSX instructions) from the latest ukb prebuilt binaries (from http://ixa2.si.ehu.es/ukb/ ) also worked.
